### ISSUE TITLE
SublimeLinter 4 will stop supporting inline settings

### ISSUE THREAD

**Issue by braver** [maristgeek/SublimeLinter-contrib-bashate#15]
We're making big changes to SublimeLinter and version 4 will no longer support inline settings. Users should migrate to configuration features of their particular linter. Linter specific settings are still supported, and can be set in sublime-project files for local configuration. If users need more flexibility than bashate provides, they could consider using shellcheck instead, it supports configuration files and many other features not present in bashate.

**Comment by bstoutenburgh** [comment]
Deprecation notice in 1.0.1 following examples from you and SublimeLinter-contrib-cmakelint.
