### ISSUE TITLE
Defining 'cls.syntax' has been deprecated

### ISSUE THREAD

**Issue by vladshved** [maristgeek/SublimeLinter-contrib-bashate#17]
Doesn't work with:
Sublime Text 3.0 build 3170
SublimeLinter v4.5.1
OSX 10.13.4

From debug log:
```
reloading plugin SublimeLinter-contrib-bashate.linter
bashate: Defining 'cls.syntax' has been deprecated. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector
```

**Comment by bstoutenburgh** [comment]
Thanks for letting me know, looks like the deprecation went into SublimeLinter 4.4.1 without any warning.
Should have a branch available for testing later today if not a new version pushed out.

**Comment by bstoutenburgh** [comment]
Should be resolved once packagecontrol.io picks up version 1.1.1.

**Comment by knagode** [comment]
I am still having this issue. HOw to fix this?

**Comment by bstoutenburgh** [comment]
Make sure you've pulled the latest updates. I do not see this for this package.

Disable the package, hit enter in the console a couple of times and enable the package again. Please send me that output.

**Comment by knagode** [comment]
@maristgeek you are right. I came trough Google but didn't notice that it is repo about another Package. I have just posted the issue where I should now. Sorry for disruption :)

**Comment by bstoutenburgh** [comment]
Ah. Good luck.
