### ISSUE TITLE
Unable to locate bashate executable

### ISSUE THREAD

**Issue by jgugliel** [maristgeek/SublimeLinter-contrib-bashate#18]
Hi,
The bashate plugin was working perfectly fine. But today I got this error message
> [Errno 2] No such file or directory: '/usr/local/bin/bashate'

A `which` gives me the following result

```
which bashate
```

> /usr/local/bin/bashate

* macOS 10.13.5
* ST 3.1.1 Build 3176

I tried restarting ST but the error's still here.

**Comment by bstoutenburgh** [comment]
How did you install `bashate`? Did you use a python 2.x version of `pip` instead of a 3.x version? Is `/usr/localbin/bashate` executable? (probably since it showed up using `which`)

Can check with `head -n1 /usr/local/bin/bashate`.

<del>For funnsies in a temporary directory can you execute these (yes, space was intentional)?
```
cat << EOF > tempfile
#!/usr/bin/env bash
  echo "hello world"

EOF

bashate -v tempfile
```
</del>

**Comment by bstoutenburgh** [comment]
More output than that one line from the Sublime console could be helpful too. That smells like it's a bit of a stack trace, the rest of it will have clues.

**Comment by bstoutenburgh** [comment]
And now seeing the [SublimeLinter 4.5.0 release message](https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.5.0.txt) I'm seeing that PATH is now kinda screwy. Can you execute these in your sublime console too?

```python
import os
print(os.environ['PATH'])
```

On a mac I now get `/usr/bin:/bin:/usr/sbin:/sbin` which is kinda garbage and something to dig into more. Seems like with Sublime 3.1+ we need to add `/usr/local/bin` to PATH per linter.

**Comment by jgugliel** [comment]
Ok, problem solved.
I tried what you suggested and realized with `head -n1 /usr/local/bin/bashate` that the interpreter was python3.6.
I recently upgraded to python3.7 with brew, and simply had to reinstall bashate.

Everything seems to be working fine now. I should have tried this earlier!

BTW, I don't have an issue with my path.
The `print(os.environ['PATH'])` gave me my full path.

Thanks
