### ISSUE TITLE
SublimeLinter-contrib-bashate doesn't work after upgrading bashate to 0.6.0

### ISSUE THREAD

**Issue by hadisfr** [maristgeek/SublimeLinter-contrib-bashate#19]
I reinstalled `bashate` yesterday (I think I did this to update to [0.6.0](https://github.com/openstack-dev/bashate/releases/tag/0.6.0)) and, after that, _SublimeLinter-contrib-bashate_ just doesn't work.

_SublimeLinter_ works correctly for other languages, there is no special message in Sublime's console (so it can find `bashate` binary), and `bashate` works correctly in command line.

I use OS X, _SublimeLinter_ 4.7.1, [_SublimeLinter-contrib-bashate_ 1.1.1](https://github.com/maristgeek/SublimeLinter-contrib-bashate/releases/tag/1.1.1), python 3.7.0, [bashate 0.6.0](https://github.com/openstack-dev/bashate/releases/tag/0.6.0), and Sublime Text 3.1.1 build 3176.

**Comment by bstoutenburgh** [comment]
What messages show up in Sublime Text's console?

**Comment by bstoutenburgh** [comment]
```bash
ben@warden816:~/bashate_testing$ bashate E002_bad.sh 
E002_bad.sh:3:1: E002 Tab indents
E002_bad.sh:3:1: E003 Indent not multiple of 4
2 bashate error(s) found
```

Excellent, `bashate` changed their output format, thanks for the heads up.

**Comment by bstoutenburgh** [comment]
Semi-related, filed https://bugs.launchpad.net/bash8/+bug/1782960 because 0.6.0 stopped distinguishing warnings from bugs.

**Comment by hadisfr** [comment]
Even though you found the exact reason, just for record: As I said, there isn't any message in sublime console and it fails silently.

**Comment by bstoutenburgh** [comment]
Cut the 2.0.0 release which will get picked up by packagecontrol.io shortly.
